auth_login/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [
    path('login/',views.login, name='login'),
    path('logout/',views.logout, name='logout'),    
] 

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('team/', include('team.urls')),
    path('auth/', include('auth_login.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team/urls.py
from django.urls import path
from django.conf import settings
from . import views

app_name = 'team'


urlpatterns = [
    path('', views.index, name='index'),                # /teams
    path('equipos/', views.teams, name='equipos'),         # /teams/teams
    path('entrenador/', views.coachs, name='entrenador'),     # /teams/coach
    path('jugador/', views.players, name='jugadores'),      # /teams/player
    path('jugador/add/', views.player_create, name='jadd'),
    path('equipos/add/', views.team_create, name='eadd'),
    path('entrenador/add/', views.coach_create, name='cadd'),
    #DELETE
    path('jugador/del/<int:pk>', views.player_delete, name='jdel'),
    path('equipos/del/<int:pk>', views.team_delete, name='edel'),
    path('entrenador/del/<int:pk>', views.coach_delete, name='cdel'),
    #UPDATE
    path('jugador/up/<int:pk>', views.player_upgrade, name='jup'),
    path('equipos/up/<int:pk>', views.team_upgrade, name='eup'),
    path('entrenador/up/<int:pk>', views.coach_upgrade, name='cup'),

    path('partido/', views.matchs, name='partido'),        # /teams/match

]

team/models.py
from django.db import models
from django.conf import settings
from datetime import date
from django.utils.safestring import mark_safe
from django.contrib.auth.models import Permission
from django.contrib.auth.models import User


import os

class Coach(models.Model):
    user = models.OneToOneField(User,null=True, blank=True, on_delete=models.CASCADE)
    #extend
    # coachName = models.CharField('Name',max_length=100)
    coachAge = models.IntegerField('Age')
    # coachEmail = models.EmailField('Email',max_length=100)
    coachRut = models.CharField('Rut',primary_key = True, max_length=50,help_text=u"with point and dash")
    # coachNickname = models.TextField('nickname',null=True, blank=True)
    class Meta:
        permissions = (("is_coach", "coach"),)   

    def __str__(self):
        return str(self.user.username)



class Team(models.Model):
    teamName = models.CharField('Name',max_length=20)
    teamDescription = models.TextField('Description')
    teamLogo = models.ImageField('Image',upload_to='./logo/',height_field=None, width_field=None, max_length=None)
    def image_logo(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.teamLogo.url))        
    image_logo.short_description = 'Imagimage_tage'
    image_logo.allow_tags = True 
    teamCode = models.AutoField(primary_key = True)
    coachRut = models.ForeignKey(Coach, on_delete=models.CASCADE,verbose_name="Coach")
    
    def __str__(self):
        return self.teamName

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

class Player(models.Model):
    playerName = models.CharField('Name',max_length=50,help_text=u"Please enter your name...")
    playerNickname = models.CharField('NickName',null=True,blank=True,max_length=50)
    playerBirthdate = models.DateField('Birthdate',auto_now=False, auto_now_add=False,help_text=u"YYYY-MM-DD") 

    def get_year(self):
        return self.playerBirthdate.year    
    def set_age(self):
        edad = date.today().year - self.get_year()  
        playerAge = models.IntegerField(edad)

    playerRut = models.CharField('Rut',primary_key = True, max_length=50,help_text=u"with point and dash")
    playerEmail = models.EmailField('Email',null=True,blank=True, max_length=254)
    playerHeight = models.FloatField('Height',help_text=u"exm : 1.70")
    playerWeight = models.FloatField('weight',help_text=u"exm : 60")
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    playerImage = models.ImageField(upload_to='uploads')
    
    def image_tag(self):
        return mark_safe('<img src="{}" width="100" />'.format(self.playerImage.url))
    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

    POSITION_CHOICES = [
    ('CE', 'Centre'),
    ('PF', 'Power Forward'),
    ('SF', 'Small Forward'),
    ('SG', 'Shooting Guard'),
    ('PG', 'Point Guard'),
]
    playerPositionGame = models.CharField('Position',max_length=60,choices = POSITION_CHOICES)

    def __str__(self):
        return self.playerName

    class Meta:
        verbose_name = 'Player'
        verbose_name_plural = 'Players'


class Match(models.Model):
    matchName = models.CharField(max_length=200)
    team1 = models.ForeignKey(Team,related_name='team1', on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team,related_name='team12', on_delete=models.CASCADE)
    date = models.DateTimeField()

    class Meta:
        verbose_name = 'Match'
        verbose_name_plural = 'Matches'
    

    def __str__(self):
        return '{name} ({team1} vs {team2})'.format(
            name=self.matchName,
            team1=self.team1,
            team2=self.team2
        ) 

team/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Team, Player, Coach

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = '__all__'
        

class PlayerForm(forms.ModelForm):

    class Meta:
        model = Player
        fields = '__all__'

# class CoachForm(forms.ModelForm):
#     class Meta:
#         model = Coach
#         fields = '__all__'

class ExtendUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )

    def save(self, commit=True):
        user = super().save(commit=True)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        else:
            print("no save pero save iwal")
            user.save()
        return user

class UserCoachExtend(forms.ModelForm):
    # coachAge = forms.IntegerField()
    # coachEmail = forms.EmailField(widget = forms.EmailInput)
    

    class Meta:
        model = Coach

        fields = (
            # 'coachName',
            'coachAge',
            # 'coachEmail',
            'coachRut',
            # 'coachNickname',
        )

team/views.py
from django.shortcuts import render, HttpResponse,redirect, get_object_or_404
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required , permission_required
# from django.urls import reverse_lazy
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib import messages
from django.contrib.auth.models import Permission
from django import forms
from .models import *
from .forms import *


@login_required
def index(request):
    template = loader.get_template('home.html')
    print("user login", request.user)
    lastFiveMatches = Match.objects.order_by('id')[:3]
    lastFivePlayers = Player.objects.order_by('playerRut')[:3]
    lastThreeCoaches = Coach.objects.order_by('coachRut')[:3]
    allTeams =  Team.objects.all()
    context = {
        'lastFiveMatches': lastFiveMatches,
        'lastFivePlayers': lastFivePlayers,
        'allTeams': allTeams,
        'lastThreeCoaches' :lastThreeCoaches,
    }
    paginadorMatches = Paginator(lastFiveMatches,3)
    paginadorPlayers = Paginator(lastFivePlayers,3)
    paginadorTeams = Paginator(allTeams,3)

    page = request.GET.get('page',1)

    try:
        context['lastFiveMatches'] = paginadorMatches.page(page)
        context['lastFivePlayers'] = paginadorPlayers.page(page)
        context['allTeams'] = paginadorTeams.page(page)
    except PageNotAnInteger:
        context['lastFiveMatches'] = paginadorMatches.page(1)
        context['lastFivePlayers'] = paginadorPlayers.page(1)
        context['allTeams'] = paginadorTeams.page(1)
    except EmptyPage:
        context['lastFiveMatches'] = paginadorMatches.page(paginadorMatches.num_pages)
        context['lastFivePlayers'] = paginadorPlayers.page(paginadorPlayers.num_pages)
        context['allTeams'] = paginadorTeams.page(paginadorTeams.num_pages)
    
    return HttpResponse(template.render(context, request))


@login_required 
def teams(request):
    template = loader.get_template('teams.html')
    allTeams = Team.objects.all()
    allCoaches = Coach.objects.all()
    players = Player.objects.all()
    context = {
        'allTeam': allTeams,
        'allplayer' : players,
        'allCoaches': allCoaches,
    }

    paginator = Paginator(allTeams,6)
    page = request.GET.get('page',1)
    try:
        context['allTeam'] = paginator.page(page)
    except PageNotAnInteger:
        context['allTeam'] = paginator.page(1)
    except EmptyPage:
        context['allTeam'] = paginator.page(paginator.num_pages)

    return HttpResponse(template.render(context,request))

@permission_required('team.is_coach')
def team_create(request):
    template = 'team_create.html'
    context = {}
    context['form'] = TeamForm(request.POST or None,files=request.FILES or None)
    if context['form'].is_valid():
        context['form'].save()
        redirect('team:equipos')

    return render(request, template, context)

@login_required()
def team_delete(request, pk):
    template = 'team_delete.html'
    context = {}
    context['team'] = Team.objects.get(pk=pk)
    
    if request.method == 'POST':
        context['team'].delete()
        return redirect('team:equipos')
    return render(request, template, context)

@login_required()
def team_upgrade(request, pk):
    template= 'team_upgrade.html'
    context = {}

    team_create = get_object_or_404(Team, pk=pk)
    context['form'] = TeamForm(instance=team_create, data=request.POST)

    if context['form'].is_valid():
        context['form'].save()
        return redirect('team:equipos')

    else:
        print("error")

    return render(request, template, context)

@login_required()
def players(request):
    template = loader.get_template('players.html')
    allTeams = Team.objects.all() 
    allPlayers = Player.objects.all()   
    context = {
        'Teams': allTeams,
        'Players' : allPlayers,
      
    }
    paginator = Paginator(allPlayers,5)
    page = request.GET.get('page',1)
    try:
        context['Players'] = paginator.page(page)
    except PageNotAnInteger:
        context['Players'] = paginator.page(1)
    except EmptyPage:
        context['Players'] = paginator.page(paginator.num_pages)

    return HttpResponse(template.render(context,request))

@login_required()
def player_create(request):
    template = 'player_create.html'
    context = {}
    context['form'] = PlayerForm(request.POST or None,files=request.FILES or None)
    if context['form'].is_valid():
        context['form'].save()
        redirect('team:jugadores')
    else:
        pass   
    return render(request, template, context)

@login_required()
def player_delete(request, pk):
    template = 'player_delete.html'
    context = {}
    context['player'] = Player.objects.get(pk=pk)
    
    if request.method == 'POST':
        context['player'].delete()
        return redirect('player:jugadores')
    return render(request, template, context)

@login_required()
def player_upgrade(request, pk):
    template= 'player_upgrade.html'
    context = {}

    player = Player.objects.get(pk=pk)
    context['form'] = PlayerForm(request.POST or None, instance=player)

    if context['form'].is_valid():
        context['form'].save()
        return redirect('player.html')

    else:
        print("error")

    return render(request, template, context)

@login_required()
def coachs(request):
    template = loader.get_template('coach.html')
    allCoaches = Coach.objects.all()
    allTeams = Team.objects.all()
    context = {
        'Coaches' : allCoaches,
        'Teams' : allTeams,
    }
    paginator = Paginator(allCoaches,5)
    page = request.GET.get('page',1)
    try:
        context['Coaches'] = paginator.page(page)
    except PageNotAnInteger:
        context['Coaches'] = paginator.page(1)
    except EmptyPage:
        context['Coaches'] = paginator.page(paginator.num_pages)
    return HttpResponse(template.render(context, request))

@login_required()
def handle_uploaded_file(f):
    with open('some/file/name.txt', 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk) 
@login_required()
def coach_create(request):
    template = 'coach_create.html'

    if request.method == "POST":
        form = ExtendUserCreationForm(request.POST)
        coach_extend = UserCoachExtend(request.POST)

        if form.is_valid() and coach_extend.is_valid():
            user = form.save()
            
            content_type = ContentType.objects.get_for_model(Coach)
            permission = Permission.objects.get(
                    codename='is_coach',
                    content_type=content_type,
                )
            user.user_permissions.add(permission)
                
            coach_profile = coach_extend.save(commit=False)
            coach_profile.user = user
        
            coach_profile.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)

            
            # login(request,user)

            messages.add_message(
                  request,
                  messages.SUCCESS,
                  'Usuario creado con éxito.'
                )

            return redirect('team:entrenador')
        else:
            messages.add_message(
              request,
              messages.ERROR,
              'Problemas al crear el usuario.'
            )            
    else:
        form = ExtendUserCreationForm()
        coach_extend = UserCoachExtend()
    
    context = {
        'form': form,
        'coach_extend': coach_extend,
    }
    return render(request, template, context)       

@login_required()
def coach_upgrade(request, pk):
    template = 'coach_upgrade.html'

    coach = get_object_or_404(Coach,pk=pk)
    if request.method == "POST":
        form = ExtendUserCreationForm(intance=coach, data=request.POST or None)
        coach_extend = UserCoachExtend(intance=coach, data=request.POST or None)
        if form.is_valid() and coach_extend.is_valid():
            user = form.save()
            coach_extend.save()
            messages.add_message(
                  request,
                  messages.SUCCESS,
                  'coach editado con éxito.'
                )
            return redirect('coach.html')
        else:
            messages.add_message(
              request,
              messages.ERROR,
              'Problemas al modificar el usuario.'
            )            
    else:
        form = ExtendUserCreationForm()
        coach_extend = UserCoachExtend()
    
    context = {
        'form': form,
        'coach_extend': coach_extend,
    }
    return render(request, template, context)       
@login_required()
def coach_delete(request, pk):
    template = 'coach_delete.html'
    context = {}
    context['coach'] = get_object_or_404(Coach, pk=pk)
    
    if request.method == 'POST':
        context['coach'].delete()
        return redirect('coach:jugadores')
    return render(request, template, context)

@login_required()
def matchs(request):
    template = loader.get_template('match.html')
    game = Match.objects.all()
    context = {
        'games':game

    }
    paginator = Paginator(game,3)
    page = request.GET.get('page',1)
    try:
        context['games'] = paginator.page(page)
    except PageNotAnInteger:
        context['games'] = paginator.page(1)
    except EmptyPage:
        context['games'] = paginator.page(paginator.num_pages)
    return HttpResponse(template.render(context, request))   

team/templates/coach.html
{% extends 'base.html' %}
<!--Breadcrumb-->
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'team:index' %}">Home</a> &rsaquo; <a href="#">Equipo</a>
</div>
{% endblock %}
<br> {% block content %}

<HR width="60%">
<div class="container">
    {% if user_type == 'ADMIN' %}
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <h3>Agregar nuevo Coach</h>
        </div>

    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <div>
                <a href="{% url 'team:cadd' %}"><button type="button" class="btn btn-info">AGREGAR</button></a>
            </div>
        </div>
    </div>
    {% endif %}
    <hr width="20%">
    <div class="row">
        <div class="col-12">

            <table class="table table-dark ">
                <thead>
                    <tr>
                        <th scope="col">Entrenadores y sus equipos</th>
                        
                    </tr>
                </thead>
                {% if perms.team.view_coach %}
                <tbody>
                    
                    {% for team in Teams  %}
                        
                        {% if team.coachRut.user.username == name %}
                        <td>{{name}}--->{{team.teamName}}</td>
                            
                        {% endif %}
                            
                    {% endfor %}
                        
                    
                </tbody>

                {% endif %}

                {%if user_type == 'ADMIN'%}
                <tbody>
                    {% for team in Teams %}
                    {% for coach in Coaches %} 
                    <tr>
                            <div class="col-5">
                                {% if team.coachRut.user.username == coach.user.username %}
                                <td>{{coach.user.username}}--->{{team.teamName}}</td>
                            </div>
                            <div class="col-1">
                                <td class="text-right">
                                    <a href="{% url 'team:cdel' coach.pk %}" class="fas fa-trash-alt " style="color:tomato;font-size: 25px;padding-right: 10px; "></a>
                                    <a href="{% url 'team:cup' coach.pk %}"><i class="fas fa-edit " style=" color:yellowgreen; font-size: 25px; "></i></a>
                                </td>
                                
                                {% endif %} 
                            </div>
                        </div>
                    </tr>
                    {% endfor %}
                    {% endfor %}
                    
                </tbody>
            {% endif %}    
            </table>
            
            <div class="pagination">
                <span class="step-links">
        {% if Coaches.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ Coaches.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ Coaches.number }} of {{ Coaches.paginator.num_pages }}.
        </span> {% if Coaches.has_next %}
                <a href="?page={{ Coaches.next_page_number }}">next</a>
                <a href="?page={{ Coaches.paginator.num_pages }}">last &raquo;</a> {% endif %}
                </span>
            </div>

        </div>
    </div>
    {% endblock content %}

team/templates/coach_create.html
{% extends 'base.html' %} 

{% block content %}
{% load bootstrap4 %}

<h5 style="background-color: tomato ;">profe cuando cree a un coach, hay que asignarle el permiso de coach view desde el admin</h2>

<form action="" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_form coach_extend %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
   Submit
  </button>
  {% endbuttons %}
</form>


{% endblock %}

team/templates/coach_delete.html
{% extends 'base.html' %}
{% block content %}

<p>¿Estas seguro de eliminar a <strong> {{coach.id}}</strong>?</p>
<form class="" method="post">
    {% csrf_token %}

    <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</button>

    <a href="{% url 'team:equipos' %}" class="btn btn-light">Cancelar</a>
</form>


{% endblock %}

team/templates/coach_upgrade.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<form action="" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_form coach_extend %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
   Submit
  </button>
  {% endbuttons %}
</form>

{% endblock %}

team/templates/match.html
{% extends 'base.html' %}
<!--Breadcrumb-->
{% load i18n %} {% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'team:index' %}">Home</a> &rsaquo; <a href="#">Partido</a>
</div>
{% endblock %}
<br> {% block content %}

<HR width="80%">
<table class="table table-dark ">
    <thead>
        <tr>
            <th scope="col">Equipos con sus jugadores</th>

        </tr>
    </thead>
    <tbody>

        {% for game in games %}
        <tr>
            <td>{{ game.matchName }} | {{game.date}} | Match: {{game.team1}} vs {{game.team2}}</td>

        </tr>
        {% endfor %}

    </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if games.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ games.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ games.number }} of {{ games.paginator.num_pages }}.
        </span> {% if games.has_next %}
    <a href="?page={{ games.next_page_number }}">next</a>
    <a href="?page={{ games.paginator.num_pages }}">last &raquo;</a> {% endif %}
    </span>
</div>
{% endblock content %}

team/templates/player_create.html
{% extends 'base.html' %} {% block content %} {% load bootstrap4 %}{% bootstrap_css %} {% bootstrap_javascript jquery='full' %}

<form action="" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-primary">
        Submit
      </button> {% endbuttons %}
</form>


{% endblock %}

team/templates/player_delete.html
{% extends 'base.html' %}
awas

team/templates/players.html
{% extends 'base.html' %}

<!--Breadcrumb-->
{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'team:index' %}">Home</a> &rsaquo; <a href="#">Jugadores</a>
</div>
{% endblock %}
<br> {% block content %}

{% if user_type == 'ADMIN' %}
<HR width="80%">
<div class="container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <h3>Agregar nuevo Jugador</h>
        </div>

    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <div>
                <a href="{% url 'team:jadd' %}"><button type="button" class="btn btn-info">AGREGAR</button></a>
            </div>
        </div>
    </div>
    {% endif %}
    <hr width="20%">
    <div class="row">
        <div class="col-12">
            <table class="table table-dark ">
                <thead>
                    <tr>
                        <th scope="col">Equipos con sus jugadores</th>
                    </tr>
                </thead>

                {% if perms.team.view_coach %}
                <tbody>
                    <tr>
                    {% for team in Teams  %}
                    {% if team.coachRut.user.username == name %}                            
                        {% for player in Players %}
                        {% if player.team == team %}
                       <td> 
                           <p style="color:white">
                            {{player.playerName}}
                            <a href="{% url 'team:jdel' player.pk %}" class="fas fa-user-times" style="color:rgb(201, 40, 40);"></a>
                            <a href="{% url 'team:jup' player.pk %}" class="fas fa-user-edit" style="color:cyan ;"></a>
                            </p>
                        </td>
                        {% endif %} 
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                </tr>
                </tbody>
                {% endif %}

                {%if user_type == 'ADMIN'%}
                <tbody>
                    {% for team in Teams %}
                    <tr>
                        <td>
                            <p>

                                <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#{{team.teamName}}" aria-expanded="false" aria-controls="collapseExample">
                                {{team.teamName}}
                                </button>
                            </p>
                            <div class="collapse" id="{{team.teamName}}">
                                <div>
                                    {% for player in Players %}
                                    {% if player.team == team %}
                                    <p style="color:black">
                                        {{player.playerName}}
                                        <a href="{% url 'team:jdel' player.pk %}" class="fas fa-user-times" style="color:rgb(201, 40, 40);"></a>
                                        <a href="{% url 'team:jup' player.pk %}" class="fas fa-user-edit" style="color:cyan ;"></a>
                                    </p>
                                </div>
                                {% endif %} {% endfor %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}    
            </table>

        </div>
    </div>
</div>


<div class="pagination ">
    <span class="step-links ">
        {% if Players.has_previous %}
            <a href="?page=1 ">&laquo; first</a>
            <a href="?page={{ Players.previous_page_number }} ">previous</a>
        {% endif %}

        <span class="current ">
            Page {{ Players.number }} of {{ Players.paginator.num_pages }}.
        </span> {% if Players.has_next %}
    <a href="?page={{ Players.next_page_number }} ">next</a>
    <a href="?page={{ Players.paginator.num_pages }} ">last &raquo;</a> {% endif %}
    </span>
</div>
{% endblock content %}t %}

team/templates/team_create.html
{% extends 'base.html' %} {% block content %}{% load bootstrap4 %}
<form action="" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %} {% bootstrap_form form %} {% buttons %}
    <button type="submit" class="btn btn-primary">
        Submit
      </button> {% endbuttons %}
</form>


{% endblock %}

team/templates/team_delete.html
{% extends 'base.html' %} {% block content %}

<p>¿Estas seguro de eliminar a <strong>{{team.id}}</strong>?</p>
<form class="" method="post">
    {% csrf_token %}

    <button type="submit" class="btn btn-danger"><i class="fas fa-trash-alt"></i> Eliminar</button>

    <a href="{% url 'team:equipos' %}" class="btn btn-light">Cancelar</a>
</form>


{% endblock %}

team/templates/teams.html
{% extends 'base.html' %} {% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'team:index' %}">Home</a> &rsaquo; <a href="#">Teams</a>
</div>
{% endblock %}
<br> {% block content %}
<hr width="80%">

{% if user_type == 'ADMIN' %}
<div class=" container">
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <h3>Agregar nuevo equipo</h>
        </div>

    </div>
    <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <div>
                <a href="{% url 'team:eadd' %}"><button type="button" class="btn btn-info">AGREGAR</button></a>
            </div>
        </div>
    </div>
    <hr width="20%">
    <div class="row ">
{% endif %}

        <div class="col-12 ">
            <table class="table table-dark ">
                <thead>
                    <tr>
                        <th scope="col ">Todos los equipos con paginación</th>

                    </tr>
                </thead>
                <tbody>

   <!-- Si es coach -->
        <!-- {% if perms.team.view_coach %} -->
        {% for team in allTeam %}
            <tr>
                <div class="row">
                {% if team.coachRut.user.username == name %}
                    <div class="col-11">
                        <td>{{ team.teamName }} </td>
                    </div>
                    <div class="col-1">
                        <td class="text-right">
                            <a href="{% url 'team:edel' team.pk %}"><i class="fas fa-trash-alt " style="color:tomato;font-size: 25px;padding-right: 10px; "></i></a>
                            <a href="{% url 'team:eup' team.pk %}"><i class="fas fa-edit " style=" color:yellowgreen; font-size: 25px; "></i></a>
                        </td>
                    </div>
                </div>
                {% endif %}
            </tr>
 
         {% endfor %}
         {% endif %}
         
<!-- si es admin -->
                {% if user_type == 'ADMIN' %}
                    {% for team in allTeam %}
                    <tr>
                        <div class="row">
                            <div class="col-11  ">
                                <td>{{ team.teamName }}</td>
                            </div>
                            <div class="col-1">
                                <td class="text-right">
                                    <a href="{% url 'team:edel' team.pk %}" class="fas fa-trash-alt " style="color:tomato;font-size: 25px;padding-right: 10px; "></a>
                                    <a href="{% url 'team:eup' team.pk %}"><i class="fas fa-edit " style=" color:yellowgreen; font-size: 25px; "></i></a>
                                </td>
                            </div>
                        </div>
                    </tr>
                        {% endfor %}
                {% endif %}
            </tbody>
        </table>

        <div class="pagination ">
            <span class="step-links ">
        {% if allTeam.has_previous %}
            <a href="?page=1 ">&laquo; first</a>
            <a href="?page={{ allTeam.previous_page_number }} ">previous</a>
        {% endif %}

        <span class="current ">
            Page {{ allTeam.number }} of {{ allTeam.paginator.num_pages }}.
        </span> {% if allTeam.has_next %}
            <a href="?page={{ allTeam.next_page_number }} ">next</a>
            <a href="?page={{ allTeam.paginator.num_pages }} ">last &raquo;</a> {% endif %}
            </span>
        </div>
    </div>


</div>{% endblock content %}